---
# file: main.yaml

- hosts: all
  become: yes
  roles:
    - role: fail2ban
      tags: fail2ban

    - role: unattended-upgrades
      tags: upgrades
      
    - role: nodejs
      tags: nodejs
    
    - role: nginx
      tags: nginx
      