---
# file: roles/unattended-upgrades/tasks/main.yaml


- name: Install packages
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges

- name: Configure unattended-upgrades
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: Configure apt-listchanges
  template: src=listchanges.conf.j2 dest=/etc/apt/listchanges.conf

- name: Create override directories for download and upgrade timers
  file: path=/etc/systemd/system/{{ item.key }}.timer state=directory
  with_dict: "{{ timer_overrides }}"

- name: Override timer schedules for download and upgrade
  template: 
    src: systemd-timer-override.j2 
    dest: /etc/systemd/system/{{ item.key }}.timer/override.conf
  with_dict: "{{ timer_overrides }}"
  notify: Restart timers
  